"""add pizza and comments datas

Revision ID: 1557afcef623
Revises: 60378a7987ab
Create Date: 2024-10-17 10:15:08.937198

"""
import os
import uuid
from datetime import datetime, UTC
from typing import Sequence, Union

import bcrypt
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1557afcef623'
down_revision: Union[str, None] = '60378a7987ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Insert realistic mock data into the `user` table
    admin1_id = uuid.uuid4()
    user_id1 = uuid.uuid4()
    user_id2 = uuid.uuid4()
    op.execute(
        """
        INSERT INTO "user" (id, name, hashed_password, email, role, disabled, created_at)
        VALUES
        ('{admin_id}', 'admin_user', '{admin_password}', 'admin@example.com', 'ADMIN', False, '{created_at}'),
        ('{user_id1}', 'john_doe', '{user_password1}', 'john.doe@example.com', 'USER', False, '{created_at}'),
        ('{user_id2}', 'jane_doe', '{user_password2}', 'jane.doe@example.com', 'USER', False, '{created_at}');
        """.format(
            admin_id=str(admin1_id),
            user_id1=str(user_id1),
            user_id2=str(user_id2),
            admin_password=bcrypt.hashpw(os.urandom(16), bcrypt.gensalt()).decode(),
            user_password1=bcrypt.hashpw(os.urandom(16), bcrypt.gensalt()).decode(),
            user_password2=bcrypt.hashpw(os.urandom(16), bcrypt.gensalt()).decode(),
            created_at=datetime.utcnow().isoformat()
        )
    )
    pizza_id1 = uuid.uuid4()
    pizza_id2 = uuid.uuid4()
    pizza_id3 = uuid.uuid4()
    pizza_id4 = uuid.uuid4()
    pizza_id5 = uuid.uuid4()
    pizza_id6 = uuid.uuid4()
    pizza_id7 = uuid.uuid4()
    pizza_id8 = uuid.uuid4()
    pizza_id9 = uuid.uuid4()
    pizza_id10 = uuid.uuid4()
    pizza_id11 = uuid.uuid4()
    pizza_id12 = uuid.uuid4()
    # Insert realistic mock data into the `pizza` table
    op.execute(
        """
        INSERT INTO "pizza" (id, name, price, image_url, description, created_at, category)
        VALUES
        ('{pizza_id1}', 'Margherita', 9.99, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Margherita_Originale.JPG/280px-Margherita_Originale.JPG', 'Classic pizza with tomato sauce and cheese', '{created_at}', 'VEGAN'),
        ('{pizza_id2}', 'Pepperoni', 12.49, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Pepperoni_Pizza_%2829204589095%29.jpg/220px-Pepperoni_Pizza_%2829204589095%29.jpg', 'Pepperoni pizza with spicy sausage', '{created_at}', 'MEAT'),
        ('{pizza_id3}', 'Hawaiian', 11.99, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Pizza_Hawaii_02.jpg/643px-Pizza_Hawaii_02.jpg', 'Pizza with ham and pineapple', '{created_at}', 'MEAT'),
        ('{pizza_id4}', 'Four Cheese', 13.50, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Pizza_quattro_formaggi_at_restaurant%2C_Chalk_Farm_Road%2C_London.jpg/280px-Pizza_quattro_formaggi_at_restaurant%2C_Chalk_Farm_Road%2C_London.jpg', 'A pizza with mozzarella, cheddar, parmesan, and gorgonzola', '{created_at}', 'VEGAN'),
        ('{pizza_id5}', 'BBQ Chicken', 14.00, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/B.B.Q._Chicken_Pizza_%2826679384893%29.jpg/800px-B.B.Q._Chicken_Pizza_%2826679384893%29.jpg?20181230000913', 'Barbecue chicken with onions and peppers', '{created_at}', 'MEAT'),
        ('{pizza_id6}', 'Veggie Delight', 10.50, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Vegetarian_pizza.jpg/800px-Vegetarian_pizza.jpg', 'A healthy pizza with a variety of fresh vegetables', '{created_at}', 'VEGAN'),
        ('{pizza_id7}', 'Meat Feast', 15.99, 'https://www.pizzalarocca.co.uk/wp-content/uploads/2021/09/meat-feast-pizza.jpg', 'A pizza loaded with bacon, sausage, ham, and pepperoni', '{created_at}', 'MEAT'),
        ('{pizza_id8}', 'Buffalo Chicken', 14.50, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Buffalo_Chicken_Deep_Dish_Pizza.png/800px-Buffalo_Chicken_Deep_Dish_Pizza.png?20220120214314', 'Buffalo chicken pizza with ranch dressing and mozzarella', '{created_at}', 'MEAT'),
        ('{pizza_id9}', 'Pesto Delight', 12.99, 'https://www.casa-di-francesco.fr/wp-content/uploads/pesto.jpg', 'A pesto-based pizza with mozzarella, tomatoes, and basil', '{created_at}', 'VEGAN'),
        ('{pizza_id10}', 'Greek Special', 13.75, 'https://pisapizza.ca/wp-content/uploads/2024/05/greek-pizza-21-001.jpg', 'Pizza with feta cheese, olives, spinach, and onions', '{created_at}', 'VEGAN'),
        ('{pizza_id11}', 'Spicy Jalapeno', 11.49, 'https://www.vindulge.com/wp-content/uploads/2023/02/Pizza-with-Jalapeno-Coppa-and-Hot-Honey.jpg', 'Pizza with jalapenos, spicy sausage, and chili flakes', '{created_at}', 'MEAT'),
        ('{pizza_id12}', 'Seafood Special', 16.50, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Seafood_pizza_%281%29.jpg/800px-Seafood_pizza_%281%29.jpg', 'A seafood pizza with shrimp, calamari, and mussels', '{created_at}', 'FISH');
        """.format(
            pizza_id1=str(pizza_id1),
            pizza_id2=str(pizza_id2),
            pizza_id3=str(pizza_id3),
            pizza_id4=str(pizza_id4),
            pizza_id5=str(pizza_id5),
            pizza_id6=str(pizza_id6),
            pizza_id7=str(pizza_id7),
            pizza_id8=str(pizza_id8),
            pizza_id9=str(pizza_id9),
            pizza_id10=str(pizza_id10),
            pizza_id11=str(pizza_id11),
            pizza_id12=str(pizza_id12),
            created_at=datetime.now(UTC).isoformat()
        )
    )
    # Insert realistic mock data into the `pizza_comment` table (3 comments per pizza)
    op.execute(
        """
        INSERT INTO "pizza_comment" (id, creator_id, pizza_id, content, created_at)
        VALUES
    -- Margherita comments
    ('{comment_id1}', '{user_id1}', '{pizza_id1}', '<b>The Margherita</b> was simple yet <i>perfect</i>!', '{created_at}'),
    ('{comment_id2}', '{user_id2}', '{pizza_id1}', 'Good, but could use a <u>bit more cheese</u>.', '{created_at}'),
    ('{comment_id3}', '{user_id1}', '{pizza_id1}', '<i>Classic pizza</i>, nothing beats <b>this one</b>.', '{created_at}'),

    -- Pepperoni comments
    ('{comment_id4}', '{user_id1}', '{pizza_id2}', 'Loved the <b>spicy</b> pepperoni!', '{created_at}'),
    ('{comment_id5}', '{user_id2}', '{pizza_id2}', 'A bit <i>oily</i>, but still <b>tasty</b>.', '{created_at}'),
    ('{comment_id6}', '{user_id2}', '{pizza_id2}', '<b>Best pepperoni pizza</b> I’ve ever had.', '{created_at}'),

    -- Hawaiian comments
    ('{comment_id7}', '{user_id2}', '{pizza_id3}', 'Pineapple on pizza is a <i>must</i> for me!', '{created_at}'),
    ('{comment_id8}', '{user_id1}', '{pizza_id3}', 'I don’t usually like pineapple, but <b>this was great</b>.', '{created_at}'),
    ('{comment_id9}', '{user_id2}', '{pizza_id3}', 'Surprisingly good combo of <i>sweet and savory</i>.', '{created_at}'),

    -- Four Cheese comments
    ('{comment_id10}', '{user_id1}', '{pizza_id4}', '<b>Cheese overload</b> in the best way possible!', '{created_at}'),
    ('{comment_id11}', '{user_id2}', '{pizza_id4}', 'Rich and <i>cheesy</i>, <u>would recommend</u>.', '{created_at}'),
    ('{comment_id12}', '{user_id1}', '{pizza_id4}', 'Could use a <b>bit more balance</b>, but still <i>good</i>.', '{created_at}'),

    -- BBQ Chicken comments
    ('{comment_id13}', '{user_id1}', '{pizza_id5}', 'BBQ sauce was <i>sweet</i> and <b>tangy</b>, perfect with the chicken.', '{created_at}'),
    ('{comment_id14}', '{user_id2}', '{pizza_id5}', 'Loved the combo of <b>chicken and peppers</b>.', '{created_at}'),
    ('{comment_id15}', '{user_id1}', '{pizza_id5}', 'Would have liked a bit more <u>BBQ sauce</u>, but still <i>delicious</i>.', '{created_at}'),

    -- Veggie Delight comments
    ('{comment_id16}', '{user_id2}', '{pizza_id6}', 'So <b>fresh</b> and <i>flavorful</i>, loved the mix of veggies.', '{created_at}'),
    ('{comment_id17}', '{user_id1}', '{pizza_id6}', 'Perfect for a <u>lighter pizza</u> option.', '{created_at}'),
    ('{comment_id18}', '{user_id2}', '{pizza_id6}', 'Could use a <i>bit more seasoning</i>, but overall <b>tasty</b>.', '{created_at}'),

    -- Meat Feast comments
    ('{comment_id19}', '{user_id1}', '{pizza_id7}', 'A <b>meat lover’s dream</b>, so much <i>flavor</i>!', '{created_at}'),
    ('{comment_id20}', '{user_id2}', '{pizza_id7}', 'Hearty and <i>filling</i>, every bite was packed with <b>meat</b>.', '{created_at}'),
    ('{comment_id21}', '{user_id1}', '{pizza_id7}', '<b>Best pizza</b> for anyone who loves a lot of <i>meat</i>.', '{created_at}'),

    -- Buffalo Chicken comments
    ('{comment_id22}', '{user_id1}', '{pizza_id8}', '<b>Spicy</b> and <i>creamy</i>, just the right amount of buffalo sauce.', '{created_at}'),
    ('{comment_id23}', '{user_id2}', '{pizza_id8}', 'Ranch and buffalo sauce combo is <b>genius</b>.', '{created_at}'),
    ('{comment_id24}', '{user_id2}', '{pizza_id8}', 'Loved the <b>tanginess</b> of the buffalo sauce with the cheese.', '{created_at}'),

    -- Pesto Delight comments
    ('{comment_id25}', '{user_id1}', '{pizza_id9}', '<b>Fresh pesto flavor</b> really shines through.', '{created_at}'),
    ('{comment_id26}', '{user_id2}', '{pizza_id9}', 'Unique and <i>delicious</i>, love the <u>basil</u>.', '{created_at}'),
    ('{comment_id27}', '{user_id2}', '{pizza_id9}', 'A lighter, <b>fresher</b> option for pizza lovers.', '{created_at}'),

    -- Greek Special comments
    ('{comment_id28}', '{user_id1}', '{pizza_id10}', 'The <b>feta cheese</b> and <i>olives</i> made this stand out.', '{created_at}'),
    ('{comment_id29}', '{user_id2}', '{pizza_id10}', 'A great combo of <u>Greek flavors</u>.', '{created_at}'),
    ('{comment_id30}', '{user_id1}', '{pizza_id10}', '<b>Spinach</b>, onions, and feta is a <i>winning combo</i>.', '{created_at}'),

    -- Spicy Jalapeno comments
    ('{comment_id31}', '{user_id2}', '{pizza_id11}', 'If you like <i>heat</i>, this pizza is for you!', '{created_at}'),
    ('{comment_id32}', '{user_id1}', '{pizza_id11}', 'The <b>jalapenos</b> bring a <u>spicy kick</u> to each bite.', '{created_at}'),
    ('{comment_id33}', '{user_id2}', '{pizza_id11}', 'Loved the <i>heat</i> from the jalapenos and sausage.', '{created_at}'),

    -- Seafood Special comments
    ('{comment_id34}', '{user_id1}', '{pizza_id12}', '<i>Fresh</i> and <b>unique</b>, seafood on pizza is a <u>game-changer</u>.', '{created_at}'),
    ('{comment_id35}', '{user_id2}', '{pizza_id12}', '<b>Delicate seafood flavors</b>, cooked perfectly.', '{created_at}'),
    ('{comment_id36}', '{user_id1}', '{pizza_id12}', 'A perfect <i>seafood blend</i>, never thought I’d love it so much!', '{created_at}');
    """.format(
            comment_id1=str(uuid.uuid4()), comment_id2=str(uuid.uuid4()), comment_id3=str(uuid.uuid4()),
            comment_id4=str(uuid.uuid4()), comment_id5=str(uuid.uuid4()), comment_id6=str(uuid.uuid4()),
            comment_id7=str(uuid.uuid4()), comment_id8=str(uuid.uuid4()), comment_id9=str(uuid.uuid4()),
            comment_id10=str(uuid.uuid4()), comment_id11=str(uuid.uuid4()), comment_id12=str(uuid.uuid4()),
            comment_id13=str(uuid.uuid4()), comment_id14=str(uuid.uuid4()), comment_id15=str(uuid.uuid4()),
            comment_id16=str(uuid.uuid4()), comment_id17=str(uuid.uuid4()), comment_id18=str(uuid.uuid4()),
            comment_id19=str(uuid.uuid4()), comment_id20=str(uuid.uuid4()), comment_id21=str(uuid.uuid4()),
            comment_id22=str(uuid.uuid4()), comment_id23=str(uuid.uuid4()), comment_id24=str(uuid.uuid4()),
            comment_id25=str(uuid.uuid4()), comment_id26=str(uuid.uuid4()), comment_id27=str(uuid.uuid4()),
            comment_id28=str(uuid.uuid4()), comment_id29=str(uuid.uuid4()), comment_id30=str(uuid.uuid4()),
            comment_id31=str(uuid.uuid4()), comment_id32=str(uuid.uuid4()), comment_id33=str(uuid.uuid4()),
            comment_id34=str(uuid.uuid4()), comment_id35=str(uuid.uuid4()), comment_id36=str(uuid.uuid4()),
            user_id1=str(user_id1), user_id2=str(user_id2),
            pizza_id1=str(pizza_id1), pizza_id2=str(pizza_id2), pizza_id3=str(pizza_id3), pizza_id4=str(pizza_id4),
            pizza_id5=str(pizza_id5), pizza_id6=str(pizza_id6), pizza_id7=str(pizza_id7), pizza_id8=str(pizza_id8),
            pizza_id9=str(pizza_id9), pizza_id10=str(pizza_id10), pizza_id11=str(pizza_id11),
            pizza_id12=str(pizza_id12),
            created_at=datetime.now(UTC).isoformat()
        )
    )

# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete mock data from `pizza_comment`, `pizza`, and `user` tables in reverse order
    op.execute("DELETE FROM pizza_comment")
    op.execute("DELETE FROM pizza")
    op.execute("DELETE FROM \"user\"")
    # ### end Alembic commands ###
